name = "portfolio-v2-web"
main = ".open-next/worker.js"
compatibility_date = "2026-10-05"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "portfolio-v2-db"
database_id = "daadbc14-9d28-45bb-8925-ad156be16dbd"
migrations_dir = "../../backend/db/migrations"
# preview_database_id = "REPLACE_WITH_PREVIEW_DATABASE_ID"

[vars]
APP_NAME = "portfolio-v2"
